function [xlawa, rlawa] = LAWAoptTTcoreLaplace(Alawa,...
                                               blawa,...
                                               x0lawa,...
                                               r0lawa,...
                                               maxIt,...
                                               tol,...
                                               stag);
% Convert
A  = LAWATENSALGConvertor.lawa2tensalgLaplaceOperator(Alawa);
b  = LAWATENSALGConvertor.lawa2tensalgCanonicalTensor(blawa);
x0 = LAWATENSALGConvertor.lawa2tensalgHTCores2TT(x0lawa, r0lawa);

% Optimize Core
s       = TTTensorALSLinearSolver(OperatorTTTensor(A),...
                                  TTTensor(b),...
                                  'x0', x0,...
                                  'maxIterations', maxIt,...
                                  'tolerance', tol,...
                                  'stagnation', stag,...
                                  'algorithm', 'dmrg');

x              = s.solve();
[xlawa, rlawa] = LAWATENSALGConvertor.tensalg2lawaTT2HTCores(x);
rlawa          = int64(rlawa);

end
